train:
  learn_rate: 0.01
  seq_len: 69
  k_splits: 2
  epochs: 100
  save_freq: 100
  smooth_data: false
  batch_size: 128
  train_size: 1654
  test_size: 1654
  shuffle: true
  tau_in: 1
  tau_out: 1
  optimizer: SGD
dataset:
  name: Uzel2022
model:
  type: NetworkLSTM
timestamp: '2023_04_02_21_52_17'
num_unique_worms: 6
