name: worm-graph
channels:
  - defaults
  - pytorch
  - pyg
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - pandas
  - psutil
  - pip
  - freetype=2.10.4
  - ipywidgets
  - jupyterlab
  - matplotlib
  - numpy
  - networkx
  - notebook
  - seaborn
  - scikit-learn
  - scikit-learn-intelex
  - scipy
  - tqdm
  - mat73
  - wget
  - pip:
    - torch-scatter -f https://data.pyg.org/whl/torch-1.12.1+cpu.html
    - torch-sparse -f https://data.pyg.org/whl/torch-1.12.1+cpu.html
    - torch-cluster -f https://data.pyg.org/whl/torch-1.12.1+cpu.html
    - torch-spline-conv -f https://data.pyg.org/whl/torch-1.12.1+cpu.html
    - torch-geometric
    - torch-geometric-temporal