name: worm-graph
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - antlr-python-runtime=4.9.3
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - babel=2.12.1
  - backcall=0.2.0
  - black=23.1.0
  - black-jupyter=23.1.0
  - blas=2.116
  - blas-devel=3.9.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cudatoolkit=11.3.1
  - cudnn=8.4.1.50
  - cycler=0.11.0
  - daal4py=2023.0.2
  - dal=2023.0.1
  - dbus=1.13.18
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - expat=2.4.9
  - fftw=3.3.9
  - flit-core=3.8.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.7.0
  - hdf5=1.10.6
  - hydra-core=1.3.2
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.1.0
  - importlib_resources=5.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=5.2.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.21.0
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=10.0.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm10=10.0.1
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.9
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - llvm-openmp=16.0.0
  - lxml=4.9.1
  - lz4-c=1.9.4
  - magma=2.6.2
  - mat73=0.60
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2022.2.1
  - mpi=1.0
  - mpich=4.0.3
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nccl=2.14.3.1
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nomkl=3.0
  - notebook-shim=0.2.2
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - omegaconf=2.3.0
  - openblas=0.3.21
  - openssl=1.1.1t
  - packaging=23.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.11.1
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - ply=3.11
  - pooch=1.4.0
  - prometheus_client=0.14.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.9
  - pytorch=1.13.1
  - pytorch-gpu=1.13.1
  - pytz=2022.7
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - scikit-learn=1.2.1
  - scikit-learn-intelex=2023.0.2
  - scipy=1.10.0
  - seaborn=0.12.2
  - send2trash=1.8.0
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.41.1
  - stack_data=0.2.0
  - tbb=2021.7.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tokenize-rt=5.0.0
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.65.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - anyio==3.6.2
      - arrow==1.2.3
      - asttokens==2.2.1
      - attrs==22.2.0
      - beautifulsoup4==4.12.0
      - bleach==6.0.0
      - cloudpickle==2.2.1
      - comm==0.1.3
      - debugpy==1.6.6
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - fqdn==1.5.1
      - future==0.18.3
      - hydra-submitit-launcher==1.2.0
      - ipykernel==6.22.0
      - ipython==8.11.0
      - isoduration==20.11.0
      - jedi==0.18.2
      - jsonpointer==2.3
      - jupyter-client==8.1.0
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==2.5.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - llvmlite==0.39.1
      - markupsafe==2.1.2
      - mistune==2.0.5
      - nbclassic==0.5.3
      - nbclient==0.7.2
      - nbconvert==7.2.10
      - nbformat==5.8.0
      - ncps==0.0.7
      - notebook==6.5.3
      - numba==0.56.4
      - numpy==1.21.6
      - platformdirs==3.1.1
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.4
      - pybind11==2.10.4
      - pyedm==1.14.0.0
      - pygments==2.14.0
      - pynamical==0.3.2
      - pyrsistent==0.19.3
      - python-json-logger==2.0.7
      - pyzmq==25.0.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - sniffio==1.3.0
      - soupsieve==2.4
      - stack-data==0.6.2
      - submitit==1.4.5
      - traitlets==5.9.0
      - uri-template==1.2.0
      - wcwidth==0.2.6
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.5.1
