name: worm-graph
channels:
  - defaults
  - pytorch
  - pyg
  - anaconda
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=1.13
  - scikit-learn-intelex
  - scikit-learn
  - ipywidgets
  - jupyterlab
  - matplotlib
  - pynamical
  - notebook
  - freetype
  - networkx
  - seaborn
  - pandas
  - numpy
  - nomkl
  - scipy
  - mat73
  - tqdm
  - pip:
      - black[jupyter]
      - hydra-core
      - omegaconf
      - pyEDM
      - wget
      - ncps
