name: worm-graph
channels:
  - defaults
  - pytorch
  - pyg
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - cpuonly
  - pytorch==1.12.1
  - pandas
  - psutil
  - pip
  - pyg
  - freetype=2.10.4
  - ipywidgets
  - jupyterlab
  - matplotlib
  - numpy
  - networkx
  - notebook
  - seaborn
  - scikit-learn
  - scikit-learn-intelex
  - scipy
  - tqdm
  - mat73
  - wget
  - pip:
    - torch-geometric-temporal