name: worm-graph-newest
channels:
  - defaults
  - anaconda
  - pytorch
  # - pyg
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.13
  - pytorch-gpu
  - scikit-learn
  # - ipywidgets
  # - jupyterlab
  - matplotlib
  - omegaconf
  - hydra-core
  - hydra-submitit-launcher
  # - pynamical=0.3.2
  # - notebook=6.5.2
  # - notebook
  # - freetype==2.12.1
  - freetype
  # - networkx=2.8.4
  - networkx
  # - seaborn=0.12.2
  - seaborn
  # - pandas=1.5.2
  - pandas
  # - numpy=1.23.5
  - numpy
  # - nomkl
  # - scipy=1.10.0
  - scipy
  # - mat73=0.60
  - mat73
  # - h5py==3.7.0
  - h5py
  # - tqdm==4.64.1
  - tqdm
  # - pyg
  # - pip==23.0.1
  - pip
  # - pip:
  #     - black[jupyter]
  #     - hydra-core=1.3.2
  #     - hydra-submitit-launcher
  #     - hydra-joblib-launcher
  #     - omegaconf=2.3.0
  #     - pyEDM=1.13.1.0
  #     - wget=3.2
  #     - ncps=0.0.7
