name: worm-graph
channels:
  - conda-forge
  - defaults
dependencies:
  - libwebp-base=1.3.0
  - xorg-libxext=1.3.4
  - parso=0.8.3
  - jupyterlab_server=2.21.0
  - libclang=15.0.7
  - glib-tools=2.74.1
  - pyparsing=3.0.9
  - libcurl=7.88.1
  - platformdirs=3.1.1
  - blas-devel=3.9.0
  - typing_extensions=4.5.0
  - executing=1.2.0
  - mysql-libs=8.0.32
  - libglib=2.74.1
  - gstreamer=1.22.0
  - libgpg-error=1.46
  - sniffio=1.3.0
  - terminado=0.17.1
  - libgfortran5=12.2.0
  - pyopenssl=23.0.0
  - gst-plugins-base=1.22.0
  - ply=3.11
  - xcb-util=0.4.0
  - libdeflate=1.17
  - certifi=2022.12.7
  - zstd=1.5.2
  - unicodedata2=15.0.0
  - babel=2.12.1
  - pyqt5-sip=12.11.0
  - asttokens=2.2.1
  - pyrsistent=0.19.3
  - libsndfile=1.2.0
  - libpq=15.2
  - libjpeg-turbo=2.1.5.1
  - pandoc=3.1.1
  - xorg-libxau=1.0.9
  - pathspec=0.11.1
  - black-jupyter=23.1.0
  - webencodings=0.5.1
  - pixman=0.40.0
  - pulseaudio-client=16.1
  - expat=2.5.0
  - libaec=1.0.6
  - black=23.1.0
  - libev=4.33
  - c-ares=1.18.1
  - xorg-xproto=7.0.31
  - jupyter_client=8.1.0
  - brotlipy=0.7.0
  - libbrotlicommon=1.0.9
  - munkres=1.1.4
  - xorg-renderproto=0.11.1
  - pooch=1.7.0
  - jupyter_server=2.5.0
  - glib=2.74.1
  - jinja2=3.1.2
  - zipp=3.15.0
  - notebook=6.5.3
  - pip=23.0.1
  - xorg-kbproto=1.0.7
  - ypy-websocket=0.8.2
  - importlib_resources=5.12.0
  - freetype=2.12.1
  - antlr-python-runtime=4.9.3
  - libbrotlienc=1.0.9
  - pure_eval=0.2.2
  - setuptools=67.6.0
  - jupyter_server_ydoc=0.8.0
  - statsmodels=0.13.5
  - xorg-libxrender=0.9.10
  - pulseaudio=16.1
  - python-fastjsonschema=2.16.3
  - nccl=2.14.3.1
  - libbrotlidec=1.0.9
  - magma=2.6.2
  - pexpect=4.8.0
  - libopus=1.3.1
  - tbb=2021.8.0
  - xorg-libxdmcp=1.1.3
  - anyio=3.6.2
  - libblas=3.9.0
  - h5py=3.8.0
  - tqdm=4.65.0
  - brotli=1.0.9
  - seaborn-base=0.12.2
  - pyyaml=6.0
  - lerc=4.0.0
  - libevent=2.1.10
  - matplotlib=3.7.1
  - prompt-toolkit=3.0.38
  - nest-asyncio=1.5.6
  - rfc3339-validator=0.1.4
  - icu=70.1
  - _openmp_mutex=4.5
  - liblapack=3.9.0
  - lz4-c=1.9.4
  - python_abi=3.9
  - contourpy=1.0.7
  - libogg=1.3.4
  - openblas=0.3.21
  - openssl=3.1.0
  - python-dateutil=2.8.2
  - urllib3=1.26.15
  - libgcrypt=1.10.1
  - libsystemd0=253
  - cycler=0.11.0
  - libcups=2.3.3
  - attr=2.5.1
  - traitlets=5.9.0
  - fftw=3.3.10
  - jsonschema=4.17.3
  - pillow=9.4.0
  - nbclassic=0.5.3
  - krb5=1.20.1
  - bleach=6.0.0
  - idna=3.4
  - libxml2=2.10.3
  - python-json-logger=2.0.7
  - numpy=1.24.2
  - stack_data=0.6.2
  - attrs=22.2.0
  - xkeyboard-config=2.38
  - jupyter_events=0.6.3
  - scikit-learn=1.2.2
  - libclang13=15.0.7
  - libsqlite=3.40.0
  - matplotlib-inline=0.1.6
  - prometheus_client=0.16.0
  - libxkbcommon=1.5.0
  - llvm-openmp=16.0.0
  - mysql-common=8.0.32
  - mypy_extensions=1.0.0
  - omegaconf=2.3.0
  - font-ttf-ubuntu=0.83
  - xorg-xf86vidmodeproto=2.3.1
  - tzdata=2022g
  - patsy=0.5.3
  - ld_impl_linux-64=2.40
  - tornado=6.2
  - pandocfilters=1.5.0
  - keyutils=1.6.1
  - libflac=1.4.2
  - xcb-util-wm=0.4.1
  - wcwidth=0.2.6
  - xcb-util-image=0.4.0
  - cudnn=8.4.1.50
  - ipywidgets=8.0.5
  - argon2-cffi-bindings=21.2.0
  - ipykernel=6.22.0
  - graphite2=1.3.13
  - python=3.9.16
  - hdf5=1.14.0
  - xorg-libsm=1.2.3
  - libllvm15=15.0.7
  - networkx=3.0
  - cudatoolkit=11.8.0
  - blas=2.116
  - openjpeg=2.5.0
  - libxcb=1.13
  - libcap=2.67
  - pkgutil-resolve-name=1.3.10
  - tokenize-rt=5.0.0
  - nbclient=0.7.2
  - click=8.1.3
  - libnsl=2.0.0
  - comm=0.1.3
  - xcb-util-renderutil=0.3.9
  - font-ttf-source-code-pro=2.038
  - mat73=0.60
  - pygments=2.14.0
  - widgetsnbextension=4.0.6
  - sleef=3.5.1
  - daal4py=2023.0.2
  - readline=8.2
  - pcre2=10.40
  - joblib=1.2.0
  - mistune=2.0.5
  - notebook-shim=0.2.2
  - nbconvert-pandoc=7.2.9
  - charset-normalizer=2.1.1
  - zlib=1.2.13
  - nbformat=5.8.0
  - libvorbis=1.3.7
  - brotli-bin=1.0.9
  - y-py=0.5.9
  - libffi=3.4.2
  - jupyterlab_widgets=3.0.6
  - xcb-util-keysyms=0.4.0
  - lame=3.100
  - xorg-xextproto=7.3.0
  - bzip2=1.0.8
  - xz=5.2.6
  - font-ttf-inconsolata=3.000
  - libhwloc=2.9.0
  - libssh2=1.10.0
  - scikit-learn-intelex=2023.0.2
  - _libgcc_mutex=0.1
  - rfc3986-validator=0.1.1
  - threadpoolctl=3.1.0
  - flit-core=3.8.0
  - ipython=8.11.0
  - libcblas=3.9.0
  - ca-certificates=2022.12.7
  - send2trash=1.8.0
  - libpng=1.6.39
  - mkl=2022.2.1
  - pandas=1.5.3
  - aiosqlite=0.18.0
  - nomkl=3.0
  - ptyprocess=0.7.0
  - nbconvert-core=7.2.9
  - jupyter_server_terminals=0.4.4
  - entrypoints=0.4
  - fonttools=4.39.2
  - pthread-stubs=0.4
  - libtiff=4.5.0
  - gstreamer-orc=0.4.33
  - psutil=5.9.4
  - json5=0.9.5
  - qt-main=5.15.8
  - fonts-conda-forge=1
  - jupyter_core=5.3.0
  - fonts-conda-ecosystem=1
  - libstdcxx-ng=12.2.0
  - markupsafe=2.1.2
  - mpich=4.0.3
  - xorg-libx11=1.8.4
  - cached_property=1.5.2
  - pulseaudio-daemon=16.1
  - libgcc-ng=12.2.0
  - nbconvert=7.2.9
  - libopenblas=0.3.21
  - importlib_metadata=6.1.0
  - cached-property=1.5.2
  - ipython_genutils=0.2.0
  - debugpy=1.6.6
  - jupyterlab=3.6.2
  - libudev1=253
  - importlib-resources=5.12.0
  - libnghttp2=1.52.0
  - dbus=1.13.6
  - jupyter_ydoc=0.2.3
  - libprotobuf=3.21.12
  - prompt_toolkit=3.0.38
  - websocket-client=1.5.1
  - backcall=0.2.0
  - toml=0.10.2
  - zeromq=4.3.4
  - jack=1.9.22
  - pytorch=1.13.1
  - libedit=3.1.20191231
  - harfbuzz=6.0.0
  - libtool=2.4.7
  - gettext=0.21.1
  - colorama=0.4.6
  - scipy=1.10.1
  - alsa-lib=1.2.8
  - liblapacke=3.9.0
  - backports=1.0
  - pyzmq=25.0.2
  - fontconfig=2.14.2
  - yaml=0.2.5
  - libgfortran-ng=12.2.0
  - nspr=4.35
  - typing-extensions=4.5.0
  - cairo=1.16.0
  - soupsieve=2.3.2.post1
  - ninja=1.11.1
  - nss=3.89
  - matplotlib-base=3.7.1
  - xorg-libice=1.0.10
  - mpi=1.0
  - cffi=1.15.1
  - libsodium=1.0.18
  - libiconv=1.17
  - pytz=2022.7.1
  - six=1.16.0
  - cryptography=39.0.2
  - pyqt=5.15.7
  - aiofiles=22.1.0
  - mpg123=1.31.3
  - libuuid=2.32.1
  - argon2-cffi=21.3.0
  - pysocks=1.7.1
  - seaborn=0.12.2
  - tomli=2.0.1
  - ncurses=6.3
  - hydra-core=1.3.2
  - pytorch-gpu=1.13.1
  - decorator=5.1.1
  - backports.functools_lru_cache=1.6.4
  - font-ttf-dejavu-sans-mono=2.37
  - packaging=23.0
  - sip=6.7.7
  - libdb=6.2.32
  - wheel=0.40.0
  - lcms2=2.15
  - beautifulsoup4=4.12.0
  - libzlib=1.2.13
  - pickleshare=0.7.5
  - tk=8.6.12
  - defusedxml=0.7.1
  - dal=2023.0.1
  - tinycss2=1.2.1
  - requests=2.28.2
  - importlib-metadata=6.1.0
  - pycparser=2.21
  - jupyterlab_pygments=0.2.2
  - jedi=0.18.2
  - kiwisolver=1.4.4
  - jupyter_server_fileid=0.8.0
  - pip:
      - future==0.18.3
      - ncps==0.0.7
      - torch-geometric==2.3.0