name: worm-graph
channels:
  - defaults
  - pytorch
  - pyg
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - freetype=2.10.4
  - pandas
  - psutil
  - ipywidgets
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - nomkl
  - networkx
  - seaborn
  - scikit-learn
  - scikit-learn-intelex
  - scipy
  - tqdm
  - mat73
  - pip:
      - torch-geometric-temporal
      - "black[jupyter]"
      - hydra-core
      - tensorboard
      - wandb
      - omegaconf
      - statsmodels
      - pyEDM
      - wget
      - ncps
