name: worm-graph
channels:
  - defaults
  - pytorch
  - pyg
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.13
  - scikit-learn-intelex
  - scikit-learn
  - ipywidgets
  - jupyterlab
  - matplotlib
  - pynamical
  - notebook
  - freetype
  - networkx
  - seaborn
  - pandas
  - numpy
  - nomkl
  - scipy
  - mat73
  - h5py
  - tqdm
  - pyg
  - pip
  - pip:
      - black[jupyter]
      - hydra-core=1.3.2
      - hydra-submitit-launcher
      - hydra-joblib-launcher
      - omegaconf=2.3.0
      - pyEDM=1.13.1.0
      - wget=3.2
      - ncps=0.0.7
