train:
  cycles: 10 # passes through multi-worm dataset
  epochs: 1 # passes through single worm dataset per cycle
  seq_len: 13 # length of sequences to train on
  learn_rate: 0.01 # learning rate
  k_splits: 7 # number of splits for interleaving train and test
  train_size: 2048 # total size of the training dataset
  test_size: 2048 # total size of the training dataset

