train:
  learn_rate: 0.01 # learning rate
  seq_len: 99 # length of sequences to train
  k_splits: 2 # number of interleaved train/test splits per single worm
  epochs: 500 # number of single worms (including repeats) processed
  save_freq: 100 # frequency (in epochs) with which to save model checkpoints
  # constraint: epochs >= num_worms &&  save_freq < epochs
  smooth_data: False # if True use the smoothed calcium data as input
  batch_size: 32 # maximum number of samples per batch
  train_size: 1654 # number of samples (sequences) of training data per epoch
  test_size: 1654 # number of samples (sequences) of validation data per epoch
  # constraint: batch_size <= min(train_size, test_size)
  shuffle: True # whether to shuffle samples from each worm
  tau_in: 1 # offset of target seqeunce from input sequence that we wish to train with
  tau_out: 1 # offset of target seqeunce from input sequence that we wish to make predictions with
  optimizer: Adam # which Pytorch optimizer to use; options: Adam, SGD, None
