analysis:
  # This directory is overwritten when using the a pipeline with train or predict submodules.
  # If using the submodule alone, this directory is the path to the log folder you want to generate the analysis in.
  analyse_this_log_dir: null # options: null, logs/hydra/<YYYY_MM_DD_HH_MM_SS>

  validation:
    # If null, user all the worms in the dataset. Otherwise, if <str> use that particular worm.
    experimental_datasets:
      # Sines0000: worm0
      # Lorenz0000: worm0
      Kato2015: worm0
      Nichols2017: worm0
      Skora2018: worm0
      Uzel2022: worm0
      Kaplan2020: worm0
      Flavell2023: worm0
      Leifer2023: worm0