analysis:
  # This directory is overwritten when using the a pipeline with train or predict submodules.
  # If using the submodule alone, this directory is the path to the log folder you want to generate the analysis in.
  analyse_this_log_dir: null # options: null, logs/hydra/<YYYY_MM_DD_HH_MM_SS>
  # Validate using some worms from each dataset
  validation:
    # null = don't analyze on this dataset
    # all = analyze all the worms in the dataset
    # <int> = use this number of (randomly picked) worms from the dataset
    # <str> = analyze the worm with this particular wormID 
    # <list> = analyze the worms with wormIDs in the list
    experimental_datasets:
      # Sines0000: all
      # Lorenz0000: all
      # VanDerPol0000: all
      Kato2015: all
      Nichols2017: all
      Skora2018: all
      Uzel2022: all
      Yemini2021: all
      Kaplan2020: all
      Flavell2023: all
      Leifer2023: all