analysis:
  # This directory is overwritten when using the a pipeline with train or predict submodules.
  # If using the submodule alone, this directory is the path to the log folder you want to (re)analyze.
  analyse_this_log_dir: null # options: null, logs/hydra/<YYYY_MM_DD_HH_MM_SS>
  # Validate final model using some/all worms from each dataset
  validation:
    # null = don't analyze on this dataset
    # all = analyze all the worms in the dataset
    # <int> = use this number of (randomly picked) worms from the dataset
    # <str> = analyze the worm with this particular wormID 
    # <list> = analyze the worms with wormIDs in the list
    experimental_datasets:
      # Sines0000: all
      # Lorenz0000: all
      # WhiteNoise0000: all
      # RandWalk0000: all
      # VanDerPol0000: all
      # Shakespeare0000: all
      Kato2015: 1
      Nichols2017: 1
      Skora2018: 1
      Kaplan2020: 1
      Yemini2021: 1
      Uzel2022: 1
      Lin2023: 1
      Flavell2023: 1
      Leifer2023: 1