analysis:
  # This directory is overwritten when using the a pipeline with train or predict submodules.
  # If using the submodule alone, this directory is the path to the log folder you want to generate the analysis in.
  analyse_this_log_dir: null

  validation:
    experimental_datasets:
      Kato2015: all
      Nichols2017: all
      Skora2018: all
      Uzel2022: all
      Kaplan2020: all
      Flavell2023: all
      Leifer2023: null
    task: 'many-to-many'