analysis:
  dataset_name: "Synthetic0000" # ["Flavell2023", "Kato2015"]
  hierarchical_clustering:
    group_by: four # None, three, four
    method: 'ward' # ward, average, complete, single
    metric: None # None, euclidean, cityblock, cosine, correlation...

  validation:
    experimental_datasets:
      Kato2015: all
      Nichols2017: all
      Skora2018: all
      Uzel2022: all
      Kaplan2020: all
      Flavell2023: all
      Leifer2023: null
    task: 'many-to-many'