dataset:
  train:
    name: Kato2015 #[Kato2015, Nichols2017, Skora2018, Uzel2022, Kaplan2020, Flavell2023, Leifer2023]
    num_named_neurons: all # number of neurons to train the model with (positive integer or 'all')
    num_worms: all # number of worms to train the model with (positive integer or 'all')
    save: false # Save the dataset after loading it (boolean)

  predict:
    name: Nichols2017 #[Kato2015, Nichols2017, Skora2018, Uzel2022, Kaplan2020, Flavell2023, Leifer2023]
    num_named_neurons: all # number of neurons to train the model with (positive integer or 'all')
    num_worms: 1 # number of worms to train the model with (positive integer or 'all')
    save: false # Save the dataset after loading it (boolean)
