# Make the train and validation dataset from scratch.
dataset:
  # Path to a directory containing the datasets to be used.
  # If null, create a new dataset in the logs/dataset directory using the source_datasets.
  # If not null, and the directory contains train and validation datasets, use them directly.
  # If not null, and the directory contains only the combined dataset, create both train and validation dataset from it.
  # If not null, and the directory contains a combined dataset plus one of the train or validation dataset, create the missing dataset using the combined dataset.
  use_these_datasets:
    path: null # options: null, data/datasets/<DatasetFolder>
    # Specify num_worms to random pick a subset worms from the combined dataset (when a combined dataset is provided).
    # If null, use all the worms in the dataset. Otherwise, if <int> use that number of worms (randomly picked) from the dataset.
    num_worms: null # options: null or <int>.

  # Whether to save the datasets in the logs/dataset directory.
  save_datasets: false

  # null = don't use this dataset
  # all = use all the worms in the dataset
  # <int> = use this number of (randomly picked) worms from the dataset
  # <str> = use this wormID particular worm in the dataset
  # <list> = use the worms with wormIDs in the list
  source_datasets:
    # # Synthetic datasets
    # Lorenz0000: null
    # RandWalk0000: null
    # Sines0000: null
    # VanDerPol0000: null
    # WhiteNoise0000: null
    # Wikitext0000: null
    # Experimental datasets
    Kato2015: all
    Nichols2017: all
    Skora2018: all
    Kaplan2020: all
    Yemini2021: all
    Uzel2022: all
    Dag2023: all
    Leifer2023: all
    Lin2023: all
    Flavell2023: all
  
  # If null, use all the named neurons from each worm. Otherwise, if <int> use that number of named neurons (randomly picked) from the each worm.
  num_named_neurons: null # number of neurons to train the model with (positive integer or null)
  # If null, use the maximum sequence length that can give the requested number of unique samples from the shortest dataset
  seq_len: null # length of the sampled neural activity sequences
  num_train_samples: 32 # number of length seq_len samples to draw from the training set per worm
  num_val_samples: 32 # number of length seq_len samples to draw from the validation set per worm
  reverse: false # whether to sample sequences in reverse order
  use_residual: false # whether to use the residual (i.e first difference) of the neural activity
  smooth_data: true # whether to use the smoothed the neural activity
  train_split_first: true # whether to use the first (true) or second (false) half of neural activity as the train half 
  train_split_ratio: 0.5 # the ratio of the neural data to assign to the train split  <int> in (0, 1)
  