# Build model from scratch
model:
  type: LinearRegression # options: LinearRegression, FeatureFFNN, NetworkLSTM, NetworkCTRNN, LiquidCfC, NeuralTransformer
  input_size: 302 # keep fixed at input_size = 302; it is the number of neurons in the adult C. elegans hermaphrodite 
  hidden_size: 256 # options: int > 0 (Note: not used by the LinearRegression model)
  loss: MSE # options: MSE, MASE, Huber, L1, Poisson # TODO: Improve implementation of MASE.
  fft_reg_param: 0.0 # how much to regularize the loss by frequency distribution matching; options: 0.0 <= float <= 1.0
  l1_reg_param: 0.0 # how much to regularize the loss by L1 norm of the model parameters; options: 0.0 <= float <= 1.0
  use_this_pretrained_model: null # options: null, logs/hydra/<YYYY_MM_DD_HH_MM_SS>/train/checkpoints/<model.pt>