model:
  type: LinearNN # options: LinearNN, NetworkLSTM, NetworkRNN, NeuralCFC, NeuralTransformer, # NetworkGCN not implemented yet
  input_size: 302 # keep fixed at input_size = 302; it is the number of neurons in the adult C. elegans hermaphrodite 
  hidden_size: 256 # options: int > 0
  loss: MSE # options: MSE, Huber, L1, Poisson
  fft_reg_param: 0.0 # how much to regularize the loss by frequency distribution matching; options: 0.0 <= float <= 1.0
  l1_reg_param: 0.0 # how much to regularize the loss by L1 norm of the model parameters; options: 0.0 <= float <= 1.0
  use_this_pretrained_model: null # options: null, path/to/pretrained/model