predict:
  # Choose the worms that you want to predict
  experimental_datasets:
    # null = don't predict on this dataset
    # all = predict on all the worms in the dataset
    # positive integer = use this number of (randomly picked) worms from the dataset
    # Sines0000: worm0
    # Lorenz0000: worm0
    Kato2015: worm0
    Nichols2017: worm0
    Skora2018: worm0
    Uzel2022: worm0
    Kaplan2020: worm0
    Flavell2023: worm0
    Leifer2023: worm0
  
  nb_ts_to_generate: null # if null, the number of time steps to generate = seq_len - context_window
  context_window: 200