# Choose the worms that you want to predict
predict:
  # This directory is overwritten when using the pipeline with the train submodule.
  # If using the submodule alone, this directory is the path to the log folder you want to (re)make predictions on.
  predict_this_log_dir: null # options: null, logs/hydra/<YYYY_MM_DD_HH_MM_SS>
  # null = don't predict on this dataset
  # all = predict all the worms in the dataset
  # <int> = use this number of (randomly picked) worms from the dataset
  # <str> = predict the worm with this particular wormID 
  # <list> = predict the worms with wormIDs in the list
  experimental_datasets:
    # Sines0000: [worm0, worm1] # test to check if distinct neuron signatures is preserved across worms
    # Lorenz0000: [worm0, worm1]
    # WhiteNoise0000: [worm0, worm1]
    # RandWalk0000: [worm0, worm1]
    # VanDerPol0000: [worm0, worm1]
    # Shakespeare0000: [worm0, worm1]
    Kato2015: worm0
    Nichols2017: worm0
    Skora2018: worm0
    Kaplan2020: worm0
    Yemini2021: worm0
    Uzel2022: worm0
    Flavell2023: worm1 # something is wrong with worm0 in Flavell2023
    Leifer2023: worm0
  
  # Number of time steps to generate 
  # null = generate all remaining time steps (max_timesteps - context_window)
  num_new_timesteps: null
  
  # Set to integer less than or equal to the value used for submodule.dataset.seq_len 
  context_window: 180