predict:
  worms_to_predict: [worm1, worm6] # if null, predict all the worms in the dataset. Otherwise, predict only the worms in this list
  nb_ts_to_generate: null # if null, the number of time steps to generate = seq_len - context_window
  context_window: 60