# Choose the worms that you want to predict
predict:
  # null = don't predict on this dataset
  # all = predict on all the worms in the dataset
  # <int> = use this number of (randomly picked) worms from the dataset
  # <str> = predict on this wormID particular worm in the dataset
  # <list> = predict on the worms with wormIDs in the list
  experimental_datasets:
    # Sines0000: [worm0, worm1] # test to check if distinct neuron signatures preserved across worms
    # Lorenz0000: worm0
    # WhiteNoise0000: worm0
    # RandWalk0000: worm0
    # VanDerPol0000: worm0
    Kato2015: worm0
    Nichols2017: worm0
    Skora2018: worm0
    Kaplan2020: worm0
    Yemini2021: worm0
    Uzel2022: worm0
    Flavell2023: worm1 # something is wrong with worm0 in Flavell2023
    Leifer2023: worm0
  
  # Number of time steps to generate 
  # null = generate all remaining time steps (max_timesteps - context_window)
  nb_ts_to_generate: null
  
  # Set to the same value as submodule.dataset.seq_len 
  context_window: 100