preprocess:
  url: https://www.dropbox.com/scl/fi/iy27cb7fcvyxfq1hocloc/opensource_data.zip?rlkey=isxaswsbdwt24lypqam05cwvl&dl=1
  zipfile: opensource_data.zip
  dataset: all # [Kato2015, Nichols2017, Skora2018, Uzel2022, Kaplan2020, Flavell2023, Leifer2023] # any dataset in utils.VALID_DATASETS
  resample_dt: 1.0 # The time interval (in seconds) to use for resampling; if null, no resampling is performed
  interpolate: linear # The method to use for interpolation; options: null, linear, quadratic, cubic
  smooth: MA
  # null: No smoothing # FFT: Fast Fourier Transform low-pass filter, # GA: Gaussian kernel filter, # ES: Exponential kernel smoothing filter, # MA: Moving average filter
