preprocess:
  opensource_url: https://www.dropbox.com/scl/fi/7sv89h78sd15da4bn3c0j/opensource_data.zip?rlkey=mcabp8wskm7nkzr2s5g9xy0ep&dl=1
  opensource_zipfile: opensource_data.zip
  presaved_url: https://www.dropbox.com/scl/fi/z6io644lqncjox9a7bcw5/presaved_datasets.zip?rlkey=3p2s21az5lf7wh0hdxlwgu48t&dl=1
  presaved_file: presaved_datasets.zip
  cleanup: true # Whether to delete the downloaded and unzipped opensource data folder
  source_dataset: all # [Kato2015, Nichols2017, Skora2018, Kaplan2020, Yemini2021, Uzel2022, Lin2023, Flavell2023, Leifer2023] # any dataset in utils.EXPERIMENT_DATASETS
  resample_dt: 0.333 #0.666 # The time interval (in seconds) to resample the neural activity at; if null, no resampling is performed
  interpolate: linear # The method to use for interpolation; options: null, linear, quadratic, cubic
  smooth: 
    # NOTE: Smoothing is done using a causal filter. Smoothing is applied before resampling.
    method: exponential # null: No smoothing, # gaussian: Gaussian convolution filter, # exponential: Exponential kernel filter, # moving: Moving average filter
    # hyperparameters of the different smoothing methods
    alpha: 0.5 # exponential; smaller alpha = smoother
    sigma: 5 # gaussian; larger sigma = smoother
    window_size: 15 # moving; larger window_size = smoother