preprocess:
  url: https://www.dropbox.com/s/icjii29um9u60zg/opensource_data.zip?dl=1
  zipfile: opensource_data.zip
  cleanup: true # Whether to delete the downloaded and unzipped opensource data folder
  source_dataset: all # [Kato2015, Nichols2017, Skora2018, Kaplan2020, Yemini2021, Uzel2022, Lin2023, Flavell2023, Leifer2023] # any dataset in utils.VALID_DATASETS
  resample_dt: 0.666 # The time interval (in seconds) to resample the neural activity at; if null, no resampling is performed
  interpolate: linear # The method to use for interpolation; options: null, linear, quadratic, cubic
  smooth: 
    # NOTE: Smoothing is done using a causal filter. Smoothing is applied before resampling.
    method: ES # null: No smoothing, # GA: Gaussian kernel filter, # ES: Exponential kernel filter, # MA: Moving average filter
    # hyperparameters of the different smoothing methods
    alpha: 0.5 # ES; smaller alpha = smoother
    sigma: 5 # GA; larger sigma = smoother
    window_size: 15 # MA; larger window_size = smoother