preprocess:
  opensource_url: https://www.dropbox.com/s/8knuzm42ka5n0by/opensource_data.zip?dl=1
  opensource_zipfile: opensource_data.zip
  presaved_url: https://www.dropbox.com/scl/fi/unfvzda4iia4uebibgilv/presaved_datasets.zip?rlkey=nb0k5zou0dnx0g9dmmumi1iv2&dl=1
  presaved_file: presaved_datasets.zip
  connectome_pub: null #[witvliet_7, witvliet_8, cook_2019, openworm, white_1986_n2u, white_1986_jsh, white_1986_jse, white_1986_whole] # A string indicating which connectome raw data file to use; if null, the default connectome is used
  cleanup: true # Whether to delete the downloaded and unzipped opensource data folder
  source_dataset: all # [Kato2015, Nichols2017, Skora2018, Kaplan2020, Yemini2021, Uzel2022, Dag2023, Lin2023, Flavell2023, Leifer2023, Venkatachalam2024] # any dataset in utils.EXPERIMENT_DATASETS
  resample_dt: 0.333 # The time interval (in seconds) to resample the neural activity at; if null, no resampling is performed
  interpolate: linear # The method to use for interpolation; options: null, linear, quadratic, cubic
  smooth: 
    # NOTE: Smoothing is done using a causal filter. Smoothing is applied prior to resampling.
    method: exponential # null: No smoothing, # gaussian: Gaussian convolution filter, # exponential: Exponential kernel filter, # moving: Moving average filter
    # hyperparameters of the different smoothing methods
    alpha: 0.5 # exponential; smaller alpha = smoother
    sigma: 5 # gaussian; larger sigma = smoother
    window_size: 15 # moving; larger window_size = smoother