train:
  task: many-to-many
  optimizer: Adam
  lr: 0.0001
  epochs: 20
  save_freq: 1000
  batch_size: 16
  shuffle: true

  early_stopping:
    delta: 1e-5 # minimum change in validation loss to be considered an improvement
    patience: 200 # number of epochs to wait for improvement before stopping

  lr_scheduler:
    T_0: 10 # Number of epochs for the first period
    T_mult: 2 # Factor to multiply T_0 after each restart
    eta_min: 1e-5 # Minimum learning rate