train:
  task: many-to-many
  optimizer: Adam
  lr: 0.0001
  epochs: 20
  save_freq: 1000
  batch_size: 16
  shuffle: true

  early_stopping:
    delta: 0 # minimum change in validation loss to be considered an improvement
    patience: 25 # number of epochs to wait for improvement before stopping