visualize:
  # This directory is overwritten when using the a pipeline with train or predict submodules.
  # If using the submodule alone, this directory is the path to the log folder you want to generate the visualization in.
  plot_figures_from_this_log_dir: null
  
  predict:
    worms_to_plot: null # if null, plot all the worms in the dataset. Otherwise, plot only the worms in this list
    neurons_to_plot: 10 # if null, plot all the neurons in the dataset. Otherwise, plot only the neurons in this list