visualize:
  # This directory is overwritten when using the a pipeline with train or predict submodules.
  # If using the submodule alone, this directory is the path to the log folder you want to generate the visualization in.
  plot_figures_from_this_log_dir: null
  
  predict:
    worms_to_plot: [worm0] # if null, plot all the worms in the dataset. Otherwise, plot only the worms in this list
    neurons_to_plot: 2 # if null, plot all the neurons in the dataset. Otherwise, plot only the neurons in this list

  # Options for scaling law plots
  scaling_law:
    exp_name: null
    log_scale: true
