visualize:
  # This directory is overwritten when using the pipeline with the train or predict submodules.
  # If using the submodule alone, this directory is the path to the log folder you want to generate the visualization in.
  plot_figures_from_this_log_dir: /om2/user/qsimeon/worm-graph/logs/hydra/2023_12_07_10_12_38 #null # options: null, logs/hydra/<FolderName> 
  
  predict:
    # if null, plot all the worms in the dataset. Otherwise, if <list> plot only the worms in that list, or if <int> plot the number of (randomly picked) worms indicated
    worms_to_plot: null # number of worms to plot
    # if null, plot all the neurons in the dataset. Otherwise, if <list> plot only the neurons in this list, or if <int> plot the number of (randomly chosen) neurons indicated
    neurons_to_plot: 3 # number of neurons to plot