visualize:
  log_dir: null # This directory is overwritten when using the a pipeline with train or predict.
                # If using the submodule alone, this directory is the path to the log folder you want to generate the visualization in.
  worm: worm0 # TODO: allow this to be a list of worms
  neuron: ALA
  use_residual: false

  # Options for scaling law plots
  scaling_law:
    exp_name: null
    log_scale: true
