defaults: # `model`, `train` are folders
  - models: models.yaml 
  - train: train.yaml
  - tasks: tasks.yaml
  - data: data.yaml
  - preprocess: preprocess.yaml

# the stuff below overwrites the defaults above
dataset:
  name: Skora2018

model:
  hidden_size: 20

# the hydra part does the hyperparameter sweep 'looping over stuff'
hydra:
  mode: MULTIRUN
  job:
    chdir: true

# can specify which .yaml file you want to use
  sweeper:
    params:
      dataset.name: Skora2018, Kaplan2020, Kato2015, Nguyen2017, Nichols2017, Uzel2022