# submitit_launcher.yaml
# @package _group_
defaults:
  - override hydra/launcher: submitit_slurm
  - _self_

hydra:
  mode: MULTIRUN
  launcher:
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 1440  # Job timeout in minutes
    cpus_per_task: 1  # Number of CPU cores per task
    gpus_per_node: null  # Number of GPUs per node (NOTE: Don't use with gres.)
    tasks_per_node: 1  # Number of tasks to run on each node
    mem_gb: 40  # Memory required per node in GB
    nodes: 1  # Number of nodes to use
    name: ${hydra.job.name}  # Name of the job
    partition: normal # Partition to submit to
    qos: null  # Quality of Service level
    comment: null  # Comment to pass to the job
    constraint: high-capacity  # Constraint specification
    exclude: dgx001, dgx002, node031, node034, node055  # Hosts to exclude
    gres: gpu:1  # Generic resources to request
    cpus_per_gpu: null  # Number of CPUs per GPU
    gpus_per_task: null  # Number of GPUs per task
    mem_per_gpu: null  # Memory per GPU
    mem_per_cpu: null  # Memory per CPU
    account: null  # Account to charge
    signal_delay_s: 120  # Delay for sending signal before timeout
    max_num_timeout: 0  # Maximum number of timeouts
    additional_parameters: {}  # Additional parameters for Slurm
    array_parallelism: 256  # Max number of simultaneous jobs
    setup:
      - cd /om2/user/qsimeon/worm-graph
